### ISSUE TITLE
Support additional file generation rules

### ISSUE THREAD

**Issue by nuta** [resea/sdk#5]
```yml
# package.yml
build:
  files:
    - path: foo/src/fsdata.c
    - depends: [foo/src/elf]
    - required_by: []
    - commands: [file2c ...]
```

```makefile
<required_by>: <path>
<path>: <depends>
    <commands>
```
